Numpy array

In [9]:
# np.array
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
# 2d array

b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3d array+float data type
c=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [15]:
# np.arange(start ,stop,step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
# with reshape(rows,columns)

np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

ARRAYS INTIALIZEATION

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3,4))

array([[0.74308996, 0.03215486, 0.0741961 , 0.73924257],
       [0.89420193, 0.8205605 , 0.79036482, 0.72177116],
       [0.0276007 , 0.94810917, 0.18772679, 0.40770402]])

In [25]:
# np.linspacace(start,stop,numbers) -->(linear space)

np.linspace(10,-10,10)

array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
         1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
        -7.77777778, -10.        ])

In [26]:
# np.identity()-->identity matrix(main diagnaol all  values are 1 and another values becom 0)

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY PROPERTIES/ATTRIBUTES

In [28]:
a1=np.arange(10)
a2=np.arange(12 , dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim  

In [ ]:
# ndim  --> is used for find diamension of matrix

a1.ndim # 1 dimention
a2.ndim # 2 dimention
a3.ndim # 3 dimention

3

Shape

In [44]:
# shape --> tells how many rows and column there

a3.shape
# output (2,2,2)--> (how many 2d array, rows , coilumns)

(2, 2, 2)

size

In [45]:
# size tells how many element are there
 
print(a3.size)

8


chaging datatype

astype

In [46]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY operation

In [26]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)

b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

scalar operatration

In [5]:
# scalar opeario--> single value * by matrix of all element

b1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
# RELATONAL 
b2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

 vector operation
 

In [13]:
b1+b2 # if both matrix shap are same 
b1*b2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

max/min/sum/prod(multiplication of all numbers)

In [28]:
np.max(b1)
np.min(b2)
np.sum(b1)
np.prod(b2)

np.int64(647647525324800)

In [ ]:
# if we want min or max a specific column or rows so we used 
# 0 -->column
#  1 --> rows

np.max(b2 ,axis=1)

# output -->  array([15, 19, 23]) it mean in first rows max valuve is 15 in 2 rows max is 19 in third is 23

np.min(b1,axis=0)

array([0, 1, 2, 3])

mean / medium/ std/var

In [30]:
np.var(b1, axis=1)

array([1.25, 1.25, 1.25])

trignometry unction (sin , cos ,teta)

In [31]:
np.sin(b1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

DOT product

In [11]:
b3=np.arange(12).reshape(3,4)
b4=np.arange(12,24).reshape(4,3)
b5 = np.arange(27).reshape(3,3,3)

np.dot(b3,b4)
b3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b4

NameError: name 'b4' is not defined

In [15]:
b5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
# slicing and indexing
b3[:1,::3]

array([[0, 3]])

iterarting

In [14]:
print("1D matrix\n")
for j in b4:
    print(j)

print("\n3D matrix\n ")

for i in np.nditer(b5):
    print(i)

1D matrix

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]

3D matrix
 
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


transpose(row to clomum and vise versa)

In [15]:
b3.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

ravel

In [16]:
b3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

horizantal stacking

In [ ]:
c1=np.arange(12).reshape(3,4)
c2=np.arange(12,24).reshape(3,4)

c2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
# horizantal 
np.hstack((b3,c1,c2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11,  8,  9, 10, 11, 20, 21, 22, 23]])

In [17]:
# virtical stacking

np.vstack((b3,c1,c2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])